# Generated by Django 4.1.7 on 2023-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('thumbnail', models.ImageField(blank=True, upload_to='covers/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
