# Generated by Django 4.1.7 on 2023-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.TextField(max_length=10),
        ),
    ]
