# Generated by Django 4.1.7 on 2023-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_message_fname_alter_message_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.TextField(max_length=10, verbose_name='Phone No.'),
        ),
    ]
