# Generated by Django 4.1.7 on 2023-03-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_message_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='address',
        ),
    ]
